target:	pa4

pa4:	main.cpp Grid.h Robot.h bulldozer.h roomba.h humanic.h optimusprime.h robocop.h kamikaze.h
	g++ -std=c++11 main.cpp Grid.cpp Robot.cpp bulldozer.cpp roomba.cpp optimusprime.cpp robocop.cpp kamikaze.cpp -o pa4

clean:
		rm pa4
